import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { auth } from "@/auth";
import { SideNav } from "@/app/(ui)/components/SideNav/SideNav";
import { getConversations } from "@/app/actions";
import "../styles/global.scss";
import styles from "./layout.module.scss";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const user = session?.user ?? null;
  const conversations = user ? await getConversations() : [];

  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body className={`${roboto.className} ${styles.body}`}>
        {user && <SideNav sessionData={user} conversations={conversations} />}
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
